# Captive portal for fallback
captive_portal:

# Web server for debugging
web_server:
  port: 80

# UART for RS485
uart:
  id: rs485
  tx_pin: GPIO3
  rx_pin: GPIO1
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

# Modbus configuration
modbus:
  id: modbus_lg
  send_wait_time: 1000ms

modbus_controller:
  - id: lg
    address: 0x1
    modbus_id: modbus_lg
    setup_priority: -10
    update_interval: 10s


button:
  - platform: restart
    id: restart_button
    name: "Рестарт ESP module"


globals:
  - id: stooklijn_target
    type: float
    restore_value: yes
    initial_value: '28'
  - id: force_update_stooklijn
    type: bool
    restore_value: no
    initial_value: 'true'


number:

# допълнителна корекция на температурата на подаване спрямо нормалната отоплителна крива
  - platform: template
    name: "Топлинен offset"
    id: wp_stooklijn_offset
    min_value: -4
    max_value: 4
    initial_value: 0
    step: 1
    restore_value: yes
    unit_of_measurement: "°C"
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(force_update_stooklijn) = true;


  - platform: modbus_controller
    modbus_controller_id: lg
    id: doel_temp_setpoint
    name: "Настройка на целева температура"
    register_type: holding
    address: 2
    value_type: U_WORD
    unit_of_measurement: "°C"
    multiply: 10
    min_value: 30
    max_value: 50
    step: 1
    write_lambda: |-
      // При запис умножаваме по 10 за да пишем правилната стойност в Modbus
      return (uint16_t)(x * 10);


#  отоплителна крива (връзка между външна температура и желана температура на подаване).
  - platform: template
    name: "Отместване на линията"
    id: overshoot_stooklijn_offset
    internal: true  
    min_value: -4
    max_value: 4
    initial_value: 0
    step: 1
    restore_value: yes
    unit_of_measurement: "°C"
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(force_update_stooklijn) = true;

  - platform: template
    id: oat_silent_always_off
    name: "Безшумно изкл на външната температура"
    min_value: 0
    max_value: 10
    step: 1
    restore_value: yes
    initial_value: 2
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:volume-plus


switch:
  
  - platform: output
    name: "Тих режим"
    id: silent_mode_switch
    output: 'modbus_set_silent_mode'
    icon: mdi:volume-off

  - platform: modbus_controller
    modbus_controller_id: lg
    id: enable_disable_switch
    name: "On/Off Термопомпа"
    register_type: coil
    address: 0
    icon: mdi:heat-pump-outline
    disabled_by_default: False
    restore_mode: ALWAYS_ON

  - platform: template
    id: stooklijn_on_off
    name: "отоп. крива според вън.темп. On/Off"
    optimistic: true
    icon: mdi:chart-bell-curve-cumulative

  - platform: template
    id: overshootcontrol_on_off
    name: "Точност на зададената темп. On/Off"
    optimistic: true
    icon: mdi:rocket

output:

  - platform: modbus_controller
    modbus_controller_id: lg
    id: modbus_set_silent_mode
    register_type: coil
    address: 2


binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Водна помпа"
    id: pump_running
    register_type: discrete_input
    skip_updates: 3
    address: 1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Компресор"
    id: compressor_running
    register_type: discrete_input
    skip_updates: 3
    address: 3

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Размразяване"
    id: defrosting
    register_type: discrete_input
    skip_updates: 3
    address: 4



sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Error code"
    id: error_code
    register_type: read
    address: 0
    value_type: U_WORD
    icon: mdi:alert-octagon

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Входна вода"
    id: water_temp_retour
    register_type: read
    address: 2
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-chevron-down
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Изходяща вода"
    id: water_temp_aanvoer
    register_type: read
    address: 3
    register_count: 2
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-chevron-up
  - platform: modbus_controller
    modbus_controller_id: lg
    id: bedrijfsmodus
    register_type: read
    address: 1
    value_type: U_WORD
  
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "температурата на стаята"
    id: binnen_temp
    register_type: read
    address: 7
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:garage-open-variant
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Flow Rate"
    id: current_flow_rate
    register_type: read
    address: 16
    register_count: 4
    device_class: "water"
    state_class: "measurement"
    unit_of_measurement: "L/m"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    lambda: |-
      if(x > 5) return x;
      else return 0.0;
    icon: mdi:waves-arrow-right
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Външна температура"
    id: buiten_temp
    register_type: read
    address: 12
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    icon: mdi:weather-cloudy
    filters:
      - multiply: 0.1
      - sliding_window_moving_average:
          window_size: 60
          send_every: 30
  
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "темп. на входен фреон"
    id: temp16
    register_type: read
    address: 16
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "темп. на изход фреон"
    id: temp17
    register_type: read
    address: 17
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Suction Temp"
    id: temp18
    register_type: read
    address: 18
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Temp"
    id: compressor_temp
    register_type: read
    address: 19
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    filters:
      - multiply: 0.1
    accuracy_decimals: 1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Condensor Temp"
    id: condensor_temp
    register_type: read
    address: 20
#    register_count: 2
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:hvac
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "High Press"
    id: high_press
    register_type: read
    address: 22
    value_type: U_WORD
    accuracy_decimals: 0
    device_class: "pressure"
    state_class: "measurement"
    unit_of_measurement: "bar"
    filters:
      - multiply: 0.01
    icon: mdi:meter-electric-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Low Press"
    id: low_press
    register_type: read
    address: 23
    value_type: U_WORD
    accuracy_decimals: 0
    device_class: "pressure"
    state_class: "measurement"
    unit_of_measurement: "bar"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Hz"
    id: compressor_rpm
    register_type: read
    address: 24
    device_class: "frequency"
    state_class: "measurement"
    unit_of_measurement: "Hz"
    value_type: U_WORD
    accuracy_decimals: 0
    icon: mdi:car-turbocharger
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Целева температура"
    id: doel_temp
    register_type: holding
    address: 2
    register_count: 6
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:home-thermometer-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Целева температура за БГВ"
    id: sww_target
    register_type: holding
    address: 8
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-water
  - platform: template
    name: "Delta T"
    id: wp_delta_t
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "K"
    accuracy_decimals: 1
    lambda: |-
      return (float)(id(corrected_water_temp_aanvoer).state-id(corrected_water_temp_retour).state); 
    update_interval: 30s
    icon: mdi:delta
  - platform: template
    name: "коригираната стойност на връщащата вода"
    id: corrected_water_temp_retour
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return (float)(id(water_temp_retour).state-0.4); 
    update_interval: 30s
    icon: mdi:thermometer-chevron-down
  - platform: template
    name: "Rounded Corrected retour"
    id: rounded_corrected_water_temp_retour
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return (float)(floor((id(corrected_water_temp_retour).state*2)+0.5)/2);
    update_interval: 30s
    icon: mdi:thermometer-chevron-down
  - platform: template
    name: "Коригирана t на подаване"
    id: corrected_water_temp_aanvoer
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return (float)(id(water_temp_aanvoer).state+0.5); 
    update_interval: 30s
    icon: mdi:thermometer-chevron-up
  - platform: template
    name: "Закръглена коригирана t на подаване"
    id: rounded_corrected_water_temp_aanvoer
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return (float)(floor((id(corrected_water_temp_aanvoer).state*2)+0.5)/2);
    update_interval: 30s
    icon: mdi:thermometer-chevron-up

text_sensor:
  - platform: template
    name: "Режим на работа"
    lambda: |-
      if (id(bedrijfsmodus).state == 0) {
        return {"Стоп"};
      } else if (id(bedrijfsmodus).state == 2) {
        return {"Отопление"};
      } else if (id(bedrijfsmodus).state == 1) {
        return {"Охлаждане"};
      } else {
        return {"Неизвестно"};
      }
    update_interval: 30s
    icon: mdi:information-outline
